### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller-hooks-contrib#1]
Which license shall we use? I'd suggest either MIT or LGPL. (We can't use GPL; we need (some) of these hooks to go within bundled pyinstaller packages.)

**Comment by htgoebel** [comment]
**Summary**
- all hooks shall be GPL-2.0-or-later
- new run-time hooks shall become Apache-2.0
- existing run-time hooks are "GPL-2.0-or-later WITH Bootloader-exception"
   - I'm going to ask the authors whether a license change is okay.

---

All hooks which are now part of PyInstaller are "GPL-2.0-or-later WITH Bootloader-exception" and need to keep this licence - except the author(s) of the respective hooks agree to a license change. The hooks within this repo are just build-tools and will not become part of any frozen application (except run-time hooks, see below), thus the exact licence of the hooks does not matter for the frozen application.

So for this repo I suggest to either keep "GPL-2.0-or-later WITH Bootloader-exception" or specify it more precisely.

With "more precisely" I mean: Strictly speaking the "Bootloader-exception" only applies to the bootloader, not the run-time hooks, which go into the frozen package. We might need a new license which states this.

For the runtime-hooks I suggest to port the principle of the "Bootloader-exception" to the run-time hooks: to be used without restrictions even in your proprietary program. Reading the GPL FAQ, I suggest to use the Apache License 2.0 for the run-time hooks:

Rational:
* Creating a new licence is to much effort.
* LGPL is not appropriate: [Section 4 for the LGPL](https://www.gnu.org/licenses/lgpl-3.0.html#section4) requires the application to include a copy of the LGPL licence and to enable the user to replace the LGPL-ed code (the run-time hook) by a different (modified) version of that code. This is neither practical nor what the "Bootloader-exception" means.
* The FSE [recommends using APL for short works](https://www.gnu.org/licenses/gpl-faq.html#WhatIfWorkIsShort), which terms to prevent contributors and distributors from suing for patent infringement.

@matysek @rasky @bjones1 Comments?

**Comment by Legorooj** [comment]
Good suggestion. APL sounds good.

**Comment by matysek** [comment]
I am ok with using Apache License for runtime hooks and change license for existing runtime hooks.

**Comment by Legorooj** [comment]
Also, shouldn't we update PyInstaller itself with this? Run time hooks technically *aren't* the bootloader.

**Comment by bjones1** [comment]
Sounds good to me.

**Comment by Legorooj** [comment]
@htgoebel are these headers alright?

### Standard hook header
```
# ------------------------------------------------------------------
# Copyright (c) 2020 PyInstaller Development Team.
#
# This file is distributed under the terms of the GNU General Public
# License (version 2.0 or later).
#
# The full license is available in LICENSE.GPL.txt, distributed with
# this software. 
#
# SPDX-License-Identifier: GPL-2.0-or-later
# ------------------------------------------------------------------
```
I've not bothered with `WITH bootloader exception`; these files aren't and never were the bootloader, so technically (legally) they are already under the standard GPL-2.

### Runtime hook header:
```
# ------------------------------------------------------------------
# Copyright (c) 2020 PyInstaller Development Team.
#
# This file is distributed under the terms of the Apache License 2.0
#
# The full license is available in LICENSE.APL.txt, distributed with
# this software.
#
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------
```

### License files:

* `LICENSE.GPL.txt` - A full copy of the *standard* GPL-2. 
* `LICENSE.APL.txt` - The text pointed out by Apache in the license (at the bottom): https://choosealicense.com/licenses/apache-2.0/

**Comment by htgoebel** [comment]
I commented on #2.

**Comment by Legorooj** [comment]
Dealt with in #2. We still need to contact people for rthooks though.
