### ISSUE TITLE
dash_html_components

### ISSUE THREAD

**Issue by KyleKing** [pyinstaller/pyinstaller-hooks-contrib#102]
**Which library is the hook for?**

`dash_html_components` ([PyPi](https://pypi.org/project/dash-html-components/))

**Have you gotten the library to work with pyinstaller?**

Yes, but it requires a hook for the data files (`hooks/hook-dash_html_components.py`). This snippet was copied from a [plotly community post](https://community.plotly.com/t/python-exe-cannot-find-default-schema-json/6864/5) and tested in a Windows environment

```py
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('dash_html_components')
```

**Additional context**

N/A

**Comment by bwoodsend** [comment]
Looks pretty textbook. Go ahead and submit a pull request for it then.
