### ISSUE TITLE
Struggling with ray import

### ISSUE THREAD

**Issue by yolking** [pyinstaller/pyinstaller-hooks-contrib#104]
System information
Windows 10
python 3.8.8
pyinstaller 4.2
ray 1.2.0

Basically I am trying to create an .exe file based on python script, where [ray](https://ray.io/) library is used, which parallelizes code execution between several processes. Script works perfectly fine in python, but I need .exe to launch this code on another computer.
I create .exe using `pyinstaller` with several manually added hidden dependencies for `ray` to work (otherwise I get ImportError)
hiddenimports=['ray.async_compat','msgpack']
Unfortunately, exe application crashes on 
```
import ray
ray.init(num_cpus=2) 
```
with

> Traceback (most recent call last):
> File "myscript.py", line 2, in
> File "ray_private\client_mode_hook.py", line 47, in wrapper
> File "ray\worker.py", line 714, in init
> File "ray\node.py", line 220, in init
> File "ray\node.py", line 827, in start_head_processes
> File "ray\node.py", line 632, in start_redis
> File "ray_private\services.py", line 833, in start_redis
> File "ray_private\services.py", line 942, in _start_redis_instance
> AssertionError

When `ray.init()` is called, it tries to launch it's dependency redis-server.exe and fails. I tried changing location of redis-server.exe in `ray` services.py source file and place it together with resulting exe file, but it didn't help. Additional files are called by services.py, which may be required for redis-server to run. Is there a way to fix it with right imports or `ray` can't be packed by `pyinstaller` due to its dependencies or parallel nature?

**Comment by bwoodsend** [comment]
Looking back at this is see [this line](https://github.com/ray-project/ray/blob/e5caaa7d1f6456cde31628ff048d68928bfe9337/python/ray/_private/services.py#L786) which means that the subprocesses being launched is another instance of https://github.com/pyinstaller/pyinstaller/issues/5902#issuecomment-859121376 which we can't solve.

**Comment by bwoodsend** [comment]
No. Unless ray changes [their offending DIY multiprocessing implementation](https://github.com/ray-project/ray/blob/e5caaa7d1f6456cde31628ff048d68928bfe9337/python/ray/_private/services.py#L786), PyInstaller will never be able to work with ray. There's nothing we can do our end. As for alternatives, I'm afraid all other freezing applications (Nuitka and cxfreeze) will have the same issue - you need a real Python installation to run it. For Windows, you should be able to install your project into one of the embedable builds from [python.org](https://www.python.org/downloads/windows/) and ship that, for Linux install your project into a docker image, for macOS I don't know. If your user base is a bit more technical then realistically I think the best cross way to ship Python projects is to [make them into setuptools distributions](https://python-packaging.readthedocs.io/en/latest/index.html) and put it somewhere public then all your users need to do is install Python then run `pip install https://github.com/your-username/your-project.git` and it'll do the rest.

**Comment by yolking** [comment]
I've switched to [aiomultiprocess](https://github.com/omnilib/aiomultiprocess) for my applications. It's much more specific though, but works with PyInstaller . I still use `ray` for other tasks, but they don't require .exe version. Maybe you should look at other multiprocess libraries too if it's possible. I haven't tried committing new issue on `ray` github -  got the feeling they wouldn't care about this problem. Maybe you should.

**Comment by rokm** [comment]
> It sounds a correct way of making the executable to see a folder of libraries that are not embedded into itself. What would you say about such an approach?

`excludes` and `pathex` influence only the build process (i.e., the analysis), it has no impact on the search paths in the actual executable. That said, your program could extend the `sys.path` to include external paths with installed python packages.

But I don't think this would help in `ray`'s case, because the problem is that spawns its sub-processes using `sys.executable`, which in frozen application is not python interpreter, but frozen application's executable. So the entry point script would need to somehow identify that its subsequent (re)-launches are part of `ray`'s attempts to spawn sub-processes, and divert the program flow accordingly (which is what we do for `multiprocessing` module, by overriding its [`freeze_support ` function](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) in our [runtime hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py)).

**Comment by stestoni** [comment]
Hi @bcaldir,

Could you elaborate on your solution please? I'm facing the same issue you used to. I'm wondering what exactly I should add before initializing ray. Thanks!

**Comment by bcaldir** [comment]
Hi @stestoni,

I actually explained the solution in the previous post. If you still have problem, could you specify it?

**Comment by stestoni** [comment]
Nevermind @bcaldir, I solved my ray problem simply bypassing the use of pyinstaller. 

For the record, though, it just wasn't clear to me what goes into `subprocess.call()` in your solution.

**Comment by quaesitor-scientiam** [comment]
@bcaldir we also have `Pyinstaller `app as well and got `ray` packaged with it.  When you run your `subprocess` call is the `ray` library still package within the `exe` or  is it in a separate location?

**Comment by bcaldir** [comment]
Hey @quaesitor-scientiam,

`ray` is both packaged within the resulting exe and installed separately in our case. To call the `ray` CLI via `subprocess` you already need a separate copy of it outside of the `exe` itself. I'm not sure though it should still be packaged or not as it already available outside of the exe but we'd had enough with this `PyInstaller` and `ray` issues that day and just worked around as explained.

**Comment by quaesitor-scientiam** [comment]
Thanks, in our case since it is going to customers so having ray separate is not an option.  Thanks for the quick reply.

**Comment by bcaldir** [comment]
You're welcome. I hope you can find another solution as the explained one is basically useless for single executable deployments.

**Comment by quaesitor-scientiam** [comment]
@bcaldir got it working via PyInstaller by including the ray executables (2 files) and include them in a local directory of the app.  That way the app is able to spin up the Ray head node and process normally.  You have to issue the `ray stop` to cleanup as well.

**Comment by mishashevelinn** [comment]
> Thank you for the reply. It makes much more sense now. You are totally right about spawning subprocesses where the correct entry point has already been lost due to the freezing approach. However, news is good!
> 
> I was thinking whether the spawning subprocesses is absolutely required or not, and started to explore the source code. It turned out that subprocess spawning points can be skipped if an ip address of a ray runtime (which was simply `auto` for automatic detection in my case as I'm running in a single node) is provided and there is a runtime that has already been started in that address via CLI command `ray start --head`. This means that the subprocess spawning lines are called from the library itself, if a copy of ray library is kept outside of the binary so the main problem we're talking here is not a concern anymore. I've added a single `subprocess.call(bla, bla)` line before `ray.init('auto')` line to initiate the processes through CLI and this workaround worked like a charm.
> 
> I'm writing this as there is no information about using ray with pyinstaller on the entire Internet as far as I saw. Thank you for your attention and fast replies!

@bcaldir Thank you for providing a workaround.
As it was mentioned here, It's not clear what to pass to `subprocess.call(bla, bla)` 
In addition - can you elaborate on the "ray kept outside"? What folder structure is possible?
Thanks alot!

**Comment by SayanBose22** [comment]
> @bcaldir we also have `Pyinstaller `app as well and got `ray` packaged with it. When you run your `subprocess` call is the `ray` library still package within the `exe` or is it in a separate location?

Thanks for all the interesting discussions. I came across exactly a same scenario as you mentioned where I have to package the exe and share it with the customer, hence cannot use the other suggestion in the thread where a different subprocess is opened. 

@quaesitor-scientiam I am curious to understand what files (2 exe referred in your comment) you added and where did you keep it. Also, did you happen to use add-data in pyinstaller to add it in your exe package? It would be great if you can kindly help share these details..
I am using ray=2.2.0 and I see only one executable in my Scripts folder as ray.exe. Please share if you are referring to something else
