### ISSUE TITLE
Hook for pyusb is broken

### ISSUE THREAD

**Issue by Bin-ze** [pyinstaller/pyinstaller-hooks-contrib#105]
The EXE package can be generated normally, but it will exit directly when opened. The problems are as follows
      Trace back (most recent call last):
        File "C:\Anaconda\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\rt hooks\pyi_rth_usb.py", line 71, in <module>
          libusb10._load_library = get_load_func('libusb10', ('usb-1.0', 'libusb-1.0', 'usb'))
      Name Error: name 'libusb10' is not defined
      [13896] Failed to execute script pyi_rth_usb
python version 3.8
I try to package a python script that does not introduce any dependent packages, but the same problem still occurs
I re-downloaded the pyintsaller package on GitHub, and the same problem still occurs
I lowered the python version to 3.5, and it still does
I tried to ignore pyinstaller -F usb.py --hidden-import pyi_rth_usb through the hidden command
, Still report an errors
what should I do？can you help me?

**Comment by Bin-ze** [comment]
if  It looks like pyi_rth_usb.py is broken ,How should I solve it? This is the first time I have used pyinstaller to encapsulate the script I wrote, and I don't have a deep understanding of the possible problems inside. It is difficult for me to solve my problems by checking all the potential errors one by one.
Can I reinstall pyinstaller.exe on other computers, can I solve this problem, or reinstall the python environment, reinstall pyinstaller in the python3.7 version, and re-execute the packaging command to solve the existing problems

**Comment by bwoodsend** [comment]
You can try an older version of pyusb and add `--clean` to your build command. But you'll probably just have to wait until one of us fixes it properly.

**Comment by rokm** [comment]
Wait, is your script/program called `usb.py`?

**Comment by Bin-ze** [comment]
I changed the name of the script from USB.py to Test.py, and found that the problem seems to have been solved. 
The generated EXE file has been running normally. I think the reason for this problem may be that my name itself conflicts with the package inside the Python system.
Thank you very much for your help!
