### ISSUE TITLE
Please restore use of GitHub Releases for new releases

### ISSUE THREAD

**Issue by mungojam** [pyinstaller/pyinstaller-hooks-contrib#131]
It looks like the publishing of GitHub releases wasn't done for the most recent release. It provides us with an easy way to watch for updates rather than having to regularly check pypi or the changelog.

The current example is that we would like to use the new plotly hook as soon as it is available. It will presumably be in the next release but we'll miss it going live unless we keep checking the Changelog.

Thanks for these hooks though, they are a really good idea!

**Comment by bwoodsend** [comment]
CC @Legorooj. A simple `gh release $(python setup.py --version)` in the releaser workflow should do it?

**Comment by Legorooj** [comment]
Done!
