### ISSUE TITLE
need hook for workflow 

### ISSUE THREAD

**Issue by zhouronghua** [pyinstaller/pyinstaller-hooks-contrib#19]
<!-- NO IMAGES --!>

**Which library is the hook for?**

 `workflow` : https://pypi.org/project/workflow/2.0.0/

**Have you gotten the library to work with pyinstaller?**

Yes, but it needs read version at running time.

**Additional context**

get metadata when packing with pyinstaller.

**Comment by Legorooj** [comment]
The hook has been added in 34e8355.
