### ISSUE TITLE
gmplot not work after doing Pyinstaller 

### ISSUE THREAD

**Issue by tingweichien** [pyinstaller/pyinstaller-hooks-contrib#20]
Everything works fine in .py file and I also successfully convert .py to .exe by pyinstaller . But when I execute the exe file gmplot.draw, it shows error about gmplot.draw and FileNotFound

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "test.py", line 792, in plotmap
    gmap.draw('map.html')
  File "site-packages\gmplot\gmplot.py", line 1050, in draw
  File "site-packages\gmplot\gmplot.py", line 1121, in _write_html
  File "site-packages\gmplot\gmplot.py", line 1187, in write_points
  File "site-packages\gmplot\gmplot.py", line 1228, in write_point
  File "site-packages\gmplot\gmplot.py", line 164, in __init__
  File "site-packages\gmplot\utility.py", line 68, in _get_embeddable_image
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI366362\\gmplot\\markers/000000.png'
```
I I tried to fix it by adding
`gmp.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"`
but still in vain

Here is my code
```
import gmplot
import webbrowser
from tkinter import *
import tkinter as tk

import os

def plotmap():
    gmp = gmplot.GoogleMapPlotter(24.28270434307802, 121.02747201919554, 14, apikey="")
    gmp.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"
    gmp.marker(24.28270434307802, 121.02747201919554)
    gmp.draw("map.html")

    webbrowser.open('map.html')


root = tk.Tk()
b = tk.Button(root, text= "plot on map", command=plotmap)
b.pack()
root.mainloop()
```

How could I fix it ????

**Comment by tingweichien** [comment]
> @amifunny good try, but you've actually got it completely wrong. If you see the path in the error: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI366362\\gmplot\\markers/000000.png'` you'll notice it's inside a `_MEIxxxxx` directory. OneFile bundles extract to a location like this, so the `gmplot` source code isn't the issue.
> 
> If you create a one directory bundle and examine the `gmplot/markers` folder, you'll find that all of the PNG files are missing, whereas if you find the `gmplot` directory in your site-packages folder the files exist.
> 
> The error is caused by PyInstaller not including the data files of `gmplot`. This error can be fixed by writing a hook for `gmplot`. See [here](https://pyinstaller.rtfd.io/en/latest/hooks.html) and a hook similar to what you'd need [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dclab.py).

@Legorooj Thanks for your reply~
I've tried adding hooks by the link you provide
First, I add the datas in hooks\hook.py 
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('C:\Python37\Lib\site-packages\gmplot')
#I also tried
#datas = collect_data_files('gmplot') 
```
Then in CMD I enter 

`pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks`
`pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks\hook.py`
 `pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --hidden-import=hooks`
but still in vain


there are some warning in the CMD about process hooking
```
10894 INFO: Processing pre-find module path hook   site
10895 INFO: site: retargeting to fake-dir 'c:\\python37\\lib\\site-packages\\PyInstaller\\fake-modules'
13237 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
20473 INFO: Analyzing hidden import 'hooks'
20543 INFO: Processing module hooks...
20543 INFO: Loading module hook "hook-certifi.py"...
20547 INFO: Loading module hook "hook-distutils.py"...
20551 INFO: Loading module hook "hook-encodings.py"...
20671 INFO: Loading module hook "hook-gevent.py"...
21165 INFO: Determining a mapping of distributions to packages...
54081 WARNING: Unable to find package for requirement zope.event from package gevent.
54081 WARNING: Unable to find package for requirement greenlet from package gevent.
54082 WARNING: Unable to find package for requirement zope.interface from package gevent.
54087 INFO: Packages required by gevent:
['setuptools', 'cffi']
```

**Comment by bwoodsend** [comment]
@amifunny The hook needs to be named after the module it's intended for. In this case it should be called `hook-gmplot.py`. 

Your first guess `pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks` is the correct one.

Also you probably need to add the `--clean` option after playing with hooks. You'll know you've got it because it'll print `INFO: Loading module hook "hook-gmplot.py"...` during build.

**Comment by tingweichien** [comment]
> @tingweichien The hook needs to be named after the module it's intended for. In this case it should be called `hook-gmplot.py`.
> 
> Your first guess `pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks` is the correct one.
> 
> Also you probably need to add the `--clean` option after playing with hooks. You'll know you've got it because it'll print `INFO: Loading module hook "hook-gmplot.py"...` during build.

@bwoodsend  thank you very much~ it finally works , bothering me for a week

so here is my final hooks
create the folder hooks and put the hook-gmplot.py inside 
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('gmplot')
#datas = collect_data_files('C:\Python37\Lib\site-packages\gmplot') will raise input error
```
and type 
`pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks`
in CMD

**Comment by tingweichien** [comment]
> > @tingweichien The hook needs to be named after the module it's intended for. In this case it should be called `hook-gmplot.py`.
> > Your first guess `pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks` is the correct one.
> > Also you probably need to add the `--clean` option after playing with hooks. You'll know you've got it because it'll print `INFO: Loading module hook "hook-gmplot.py"...` during build.
> 
> @bwoodsend thank you very much~ it finally works , bothering me for a week
> 
> so here is my final hooks
> create the folder hooks and put the hook-gmplot.py inside
> 
> ```
> from PyInstaller.utils.hooks import collect_data_files
> datas = collect_data_files('gmplot')
> #datas = collect_data_files('C:\Python37\Lib\site-packages\gmplot') will raise input error
> ```
> 
> and type
> `pyinstaller -F GUI_split.py --icon=.\image\dragonfly_ico.ico --additional-hooks-dir hooks`
> in CMD

**Comment by Legorooj** [comment]
@amifunny would you be able to submit a PR with a hook for gmplot? To this repository.

**Comment by bwoodsend** [comment]
@tingweichien We'll close this after the fixing hook is committed (either by you or one of us).

**Comment by tingweichien** [comment]
> @tingweichien We'll close this after the fixing hook is committed (either by you or one of us).

okay, no problem

**Comment by amifunny** [comment]
@Legorooj Pull request for gmplot hook is added. See https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/21.
