### ISSUE TITLE
sklearn.utils._weight_vector hidden import not found

### ISSUE THREAD

**Issue by SiphonDuck** [pyinstaller/pyinstaller-hooks-contrib#277]
## Description of the issue

`sklearn.utils.weight_vector` has been made private in https://github.com/scikit-learn/scikit-learn/pull/15225.
The correct hidden import is now: `sklearn.utils._weight_vector`.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.4```
* Version of Python: ```3.9.5```
* Platform: ```Windows```
* Did you also try this on another platform? Does it work there? ```I think the problem is independent of the platform.```

> * try the latest development version, using the following command:
> 
> ```shell
> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
> ```
> 
> * follow *all* the instructions in our "If Things Go Wrong" Guide
>   (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and
> 
> ### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)
> 
>   * [ ] start with clean installation
>   * [ ] use the latest development version
>   * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
>   * [ ] Package your program in **--onedir mode**
>   * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
>   * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

As long as I can see, on ```develop``` nothing changes about this issue.

### A minimal example program which shows the error

test.py:
```
import sklearn
```

Trying to build it:
```
pyinstaller test.py
```

### Stacktrace / full error message

```
24840 WARNING: Hidden import "sklearn.utils.lgamma" not found!
24840 WARNING: Hidden import "sklearn.utils.weight_vector" not found!
```

These hidden imports are located at ..\site-packages\\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-sklearn.metrics.cluster.py

```
hiddenimports = [
    'sklearn.utils.lgamma',
    'sklearn.utils.weight_vector'
]
```

### Possible resolution
Change `sklearn.utils.weight_vector` to  `sklearn.utils._weight_vector`.
I don't know about `sklearn.utils.lgamma` as I can't seem to find it in the current version of sklearn, but in my experience adding `sklearn.utils._weight_vector` to the hidden imports fixed any issues, so it might now be an unnecessary import.

**Comment by bwoodsend** [comment]
Go ahead and make a pull request then...

**Comment by SiphonDuck** [comment]
I apologize, but I'm very new to Github and I don't honestly know how to do that, may you point me to some guide/manual or give me some directions on how to do that?
Thanks in advance.

**Comment by bwoodsend** [comment]
The guide is [here](https://github.com/bwoodsend/pyinstaller-hooks-contrib/tree/readme#i-want-to-help) at the moment but it's maybe best if I just do it then.

**Comment by SiphonDuck** [comment]
Perfect, thank you very much.

**Comment by bwoodsend** [comment]
Actually, #276 probably already fixed this. Can you retry with the development version?

```
pip install https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/master.zip
```
Then rebuild but add the `--clean` option.

**Comment by rokm** [comment]
Those warnings will be there even with #276, because that's an older hook that unconditionally adds those (now non-existant) hidden-imports. 

I suppose a version check should be added to the hook (>= 0.21 based on comment, and < the version that renamed the modules); but `sklearn.utils._weight_vector` itself should be picked up, although probably by one of the newer scikit-learn hooks.
