### ISSUE TITLE
Hooks for cairocffi and cairosvg with or without binaries?

### ISSUE THREAD

**Issue by wf-r** [pyinstaller/pyinstaller-hooks-contrib#346]
Hi,

I would like to provide hooks for cairocffi and cairosvg. Both have a VERSION file which needs to be added to datas, which is no problem.
However, both also rely on loading cairo libraries which need to be installed by the user (and also rely on further libraries). Should these libraries and their dependencies be added as binaries (using ctypes.util.find_library) in the hook, or would you like to stay away from this complexity?

Best
Wolfgang

**Comment by rokm** [comment]
Are the `cairo` libraries linked against (e.g., by package's binary extension module), or are they dynamically loaded at run-time (e.g., via `dlopen()` or equivalent)? If the former is the case, they should be automatically picked up by our binary dependency scanner. If not, the `cairo` library (or whichever libraries are loaded at runtime) should be discovered by the hook and added to binaries, while their linked dependencies should then be automatically picked up by the dependency scanner. But overall, I think we should collect these shared libraries.

**Comment by wf-r** [comment]
It's the latter (`dlopen()` is used).

Great, thanks for the quick response, will do as you suggested.
