### ISSUE TITLE
 PySide2 5.15 hook fails to import shiboken2 dll

### ISSUE THREAD

**Issue by maicol07** [pyinstaller/pyinstaller-hooks-contrib#42]
**Describe the bug**

*   Which hook/library isn't working? PySide2
*   Does the error get raised while building or when running?

More info are in this issue: pyinstaller/pyinstaller#4913 since this is related to the pyside2 hook

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Python Version: 3.8.5
*   Version of `pyinstaller-hooks-contrib`: 2020.4
*   Version of PyInstaller 4.0

**Comment by Legorooj** [comment]
PySide hooks are kept in PyInstaller. Closing in favour of pyinstaller/pyinstaller#4913
