### ISSUE TITLE
`hook-pylint.py` filter seems to be out of date

### ISSUE THREAD

**Issue by kkaja123** [pyinstaller/pyinstaller-hooks-contrib#435]
https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/8f66a66b89e76e6213972fde1c84a337b11fbd5d/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylint.py#L63-L66

Line 65: [I don't think the `pylint.test` package exists (at least not currently)](https://github.com/PyCQA/pylint/tree/main/pylint).

Line 66:
```python
not name == 'testutils'
```
should really be
```python
not is_module_or_submodule(name, 'pylint.testutils')
```

**Desktop:**
 - OS: Windows 10
 - Python Version: Python 3.9.5
 - Version of `pyinstaller-hooks-contrib`: 2022.4
 - Version of PyInstaller: 5.1

**Additional context**
Mentioned in https://github.com/pyinstaller/pyinstaller/issues/6846

**Comment by bwoodsend** [comment]
They have both existed at some point in the past (see [test](https://github.com/PyCQA/pylint/commits/main/pylint/test) and [testutils](https://github.com/PyCQA/pylint/commits/main/pylint/testutils)). But you're right about line 66.
