### ISSUE TITLE
ModuleNotFoundError: No module named 'yt_dlp.compat._legacy'

### ISSUE THREAD

**Issue by aliencaocao** [pyinstaller/pyinstaller-hooks-contrib#438]
Unable to launch compiled exe using [yt_dlp ](https://github.com/yt-dlp/yt-dlp) library. If I run the python .py file, works fine.
Was able to do it in PyInstaller 5.0.

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import yt_dlp
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "yt_dlp\compat\__init__.py", line 14, in <module>
  File "yt_dlp\compat\compat_utils.py", line 36, in passthrough_module
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'yt_dlp.compat._legacy'
[22836] Failed to execute script 'main' due to unhandled exception!
```

Code:
```
import yt_dlp
```

Compiled with `pyinstaller --log-level DEBUG -F --add-data "libopus-0.dll;." --distpath ./ --clean --upx-dir upx/ --noconfirm main.py`

**Comment by bwoodsend** [comment]
You can submit a hook for it if you want. I'd much rather that `yt_dlp` stopped doing [their hairy dynamic imports hacks](https://github.com/yt-dlp/yt-dlp/blob/1d485a1a799bbeeb2faea0595676ca7d4c0f3716/yt_dlp/compat/compat_utils.py).

**Comment by jlw4049** [comment]
Should I post an issue on their tracker?

**Comment by bwoodsend** [comment]
Hmm, you can if you want. I'd be surprised if they got rid of it just for our benefit.

**Comment by jlw4049** [comment]
So should we, for now just use the command line 
--hidden-import=yt_dlp.compat._legacy

**Comment by pukkandan** [comment]
The "hairy dynamic imports hacks" is necessary for us to be able to deprecate (and issue warnings for) legacy functions without actually breaking the extractor API. I have now made yt-dlp handle the import failure of `compat._legacy` gracefully. So the hook is no longer needed as long as you don't actually try to access a legacy function.

But this got me wondering - is there any way to specify in yt-dlp itself that the package has hidden imports, so that hooks don't need to be maintained separately?

**Comment by bwoodsend** [comment]
> The "hairy dynamic imports hacks" is necessary for us to be able to deprecate (and issue warnings for) legacy functions without actually breaking the extractor API.

What's wrong with just putting `warnings.warn("blah blah blah", category=DeprecationWarning)` in the first line of the deprecated function's body? You could put the warning into a function/decorator if there's lots of them like NumPy does.

> But this got me wondering - is there any way to specify in yt-dlp itself that the package has hidden imports, so that hooks don't need to be maintained separately?

There is ([docs](https://pyinstaller.org/en/v5.2/hooks.html#provide-hooks-with-package)) but it's not the most streamlined process. For hidden imports specifically there's a lame alternative of putting explicit imports inside a block of never executed code:
```python
if False:
    yt_dlp.compat._legacy
```

**Comment by pukkandan** [comment]
This hook is not necessary since [2022.07.18](https://github.com/yt-dlp/yt-dlp/commit/f5e438a976dcf8d7d263631ea0b0bf114b6182af). We are now also [providing hooks ourselves](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/__pyinstaller/hook-yt_dlp.py). I suggest removing the hook here

**Comment by bwoodsend** [comment]
[Gone](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/3807cb660a645b45ab1fd358bc0cbe7bb18ab5ce/CHANGELOG.rst#removed-hooks)!
