### ISSUE TITLE
Include hook for compliance_checker package

### ISSUE THREAD

**Issue by ykern** [pyinstaller/pyinstaller-hooks-contrib#517]
**Is your feature request related to a problem? Please describe.**
I am building an app with [fbs](https://github.com/mherrmann/fbs) which uses PyInstaller in the background. In the app I am using the [compliance_checker](https://github.com/ioos/compliance-checker) (v.5.0.2) module. When bundling the app this module does not get packed correctly.

**Describe the solution you'd like**
I added a simple hook for this module and would like to hereby contribute it to the project. 

**Additional context**
Unfortunately, I can't check the hook on other systems than Linux. But I would think it would not be different there.
I am first creating the issue here and the link to it in the merge request.

Just as a hint: The compliance_checker hook solved to problem for that module to work but another issue appeared for the module [shapely](https://github.com/shapely/shapely) (v.1.7.1) which gets imported from compliance_checker. There is a related discussion to that [here](https://github.com/shapely/shapely/issues/1385). I basically wrote a hook for that as well but it is too specific for now to create a merge request from it. So this just as a workaround or hint for anyone that has the same issue or wants to take this further.

**Comment by rokm** [comment]
A simple `import compliance_checker` program seems to crash with
```
Traceback (most recent call last):
  File "program.py", line 1, in <module>
    import compliance_checker
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "compliance_checker/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "netCDF4/__init__.py", line 3, in <module>
  File "src/netCDF4/_netCDF4.pyx", line 1237, in init netCDF4._netCDF4
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "cftime/__init__.py", line 1, in <module>
  File "src/cftime/_cftime.pyx", line 15, in init cftime._cftime
ModuleNotFoundError: No module named 'cftime._strptime'
```

and (if `cftime` is added to `hiddenimports`) with:
```
Traceback (most recent call last):
  File "program.py", line 1, in <module>
    import compliance_checker
  File "pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
    exec(bytecode, module.__dict__)
  File "compliance_checker/__init__.py", line 6, in <module>
  File "pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
    exec(bytecode, module.__dict__)
  File "netCDF4/__init__.py", line 3, in <module>
  File "src/netCDF4/_netCDF4.pyx", line 1237, in init netCDF4._netCDF4
  File "pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
    exec(bytecode, module.__dict__)
  File "cftime/__init__.py", line 1, in <module>
  File "src/cftime/_cftime.pyx", line 15, in init cftime._cftime
ModuleNotFoundError: No module named 'cftime._strptime'
```

And collecting `cftime` submodules makes the simple import program run.

These should be solved by hooks for `netCDF4` and `cftime`, though.

---

What error are you getting in your program (which presumably makes actual use of `compliance_checker`'s functionality)? Does the data `compliance_checker/data/` need to be collected? Are there any missing submodules from `compliance_checker` that need to be collected? 

Using `collect_all` implicitly solved all these potential problems, but for "official" hook, we should solve these problems with finer granularity...

**Comment by ykern** [comment]
Thanks for further information. I wasn't sure what would be the best way to contribute this. Your points are very valid and I will investigate this and also check out the info from https://github.com/pyinstaller/pyinstaller-hooks-contrib (did not know about that link before) and follow up.

**Comment by ykern** [comment]
Since I am using PyInstaller=3.4 I had to use a simple workaround to exclude not needed directories like `tests`. My current setup does not allow a newer PyInstaller version where flags like `exclude` are available in the collect functions (was added later: https://github.com/pyinstaller/pyinstaller/issues/5113).

The following works for me but does unfortunately not help to create an "official" hook:
```python
from PyInstaller.utils.hooks import collect_all

datas_all, binaries, hiddenimports_all = collect_all('compliance_checker')

# exclude not needed directories
datas = []
for ele in datas_all:
	if not 'tests' in ele[1]:
		datas.append(ele)
		
hiddenimports = []
for ele in hiddenimports_all:
	if not 'tests' in ele:
		hiddenimports.append(ele)
```
Other directories than the excluded `compliance_checker/tests` seems to be required for `compliance_checker` to work properly. I currently don't have the capacity to take this further. But if one wants to build an "official" hook for the newer versions of PyInstaller I would look into the `exclude` options of the collect methods.

The code shown [here](https://github.com/ioos/compliance-checker#python-usage) can be used to set up a test for `compliance_checker`. As example file one could use a file provided in the `compliance_checker/tests/data` directory.

**Comment by rokm** [comment]
Thanks for the info!

> Since I am using PyInstaller=3.4 I had to use a simple workaround to exclude not needed directories like tests.

PyInstaller 3.4 is old and unsupported, and likely contains bugs that were addressed in later versions. Also, I think the support for discovery and loading of external hooks (such as the ones from this repository) was added in PyInstaller 4.x. 

> I currently don't have the capacity to take this further. 

That's fair; I'll take over from here and see about making a test and a hook for `compliance_checker` (and its dependencies).
