### ISSUE TITLE
June release / release schedule

### ISSUE THREAD

**Issue by davetapley** [pyinstaller/pyinstaller-hooks-contrib#606]
It _appears_ that releases are roughly monthly?
https://github.com/pyinstaller/pyinstaller-hooks-contrib/releases

Can we get a June release? 😁 
https://github.com/pyinstaller/pyinstaller-hooks-contrib/compare/2023.3...master

Happy to make a PR if easier.

Thanks!

**Comment by bwoodsend** [comment]
You're right. I'll go press my button!
