### ISSUE TITLE
for python3 it is no need `prettytable` hooks

### ISSUE THREAD

**Issue by rqx110** [pyinstaller/pyinstaller-hooks-contrib#683]
as title

**Comment by bwoodsend** [comment]
What makes you think that? The offending [query to its own package metadata](https://github.com/jazzband/prettytable/blob/13830720470f39b0d8983a9c2493c803cd538e12/src/prettytable/__init__.py#L49) is still there and deleting that hook leads to a `importlib.metadata.PackageNotFoundError: No package metadata was found for prettytable` error.

**Comment by rqx110** [comment]
you are right! I missing this. Thanks!
