### ISSUE TITLE
sklearn dropped neighbors._typedef in version 1.0.2

### ISSUE THREAD

**Issue by theresaschneids** [pyinstaller/pyinstaller-hooks-contrib#697]
**Describe the bug**
The module sklearn.neighbors._typedef was removed from the sklearn package in 1.0.2
[Present in 1.0.1](https://github.com/scikit-learn/scikit-learn/tree/1.0.1/sklearn/neighbors)
[Removed in 1.0.2](https://github.com/scikit-learn/scikit-learn/tree/1.0.2/sklearn/neighbors)

The hidden imports in hook-sklearn.neighbors.py require `sklearn.neighbors._typedef` for all versions >=0.22, so a warning is thrown

* Which hook/library isn't working? 
[hook-sklearn.neighbors.py](https://github.com/rokm/pyinstaller-hooks-contrib/blob/d2f155a8b997f410e330a9fecdbe5ccae016f840/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.neighbors.py)

* Does the error get raised while building or when running?
Building

**To Reproduce**

A minimal example file:
```python
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
scaler.fit(data)
```

PyInstaller command:
```
pyinstaller --clean --onefile test.py
```

Error:
```
47783 WARNING: Hidden import "sklearn.neighbors._typedefs" not found!
```

**Expected behavior**
I expected that, if I added `--hidden-import="sklearn.neighbors._typedefs"` to my pyinstaller command, that I would no longer receive the warning, but it persisted, leading me to look closer into the cause of the warning. I expected my sklearn version (version 1.3.2) to require sklean.neighbords._typedefs, but I found that it was removed in version 1.0.2. 

**Screenshots**
![image](https://github.com/pyinstaller/pyinstaller-hooks-contrib/assets/114548281/b72816a0-4fdd-4086-92bb-ba3326a21c54)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version: 3.11.7
 - Version of `pyinstaller-hooks-contrib`: 2023.10
 - Version of PyInstaller 6.1.0

**Additional context**
I propose the solution of editing lines 17-28 of [hook-sklearn.neighbors.py](https://github.com/rokm/pyinstaller-hooks-contrib/blob/d2f155a8b997f410e330a9fecdbe5ccae016f840/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.neighbors.py) as follows
```python

if is_module_satisfies("scikit_learn > 1.0.1"):
    # 1.0.2 and later
    hiddenimports += [
        'sklearn.neighbors._quad_tree',
    ]
elif is_module_satisfies("scikit_learn < 0.22 "):
    # 0.21 and below
    hiddenimports += [
        'sklearn.neighbors.typedefs',
        'sklearn.neighbors.quad_tree',
    ]
else:
    # between and including 0.22 and 1.0.1
    hiddenimports += [
        'sklearn.neighbors._typedefs',
        'sklearn.neighbors._quad_tree',
    ]
```

**Comment by bwoodsend** [comment]
Sounds good to me. If you're willing to make that update then go for it.
