### ISSUE TITLE
Add PyInstaller in 'I want to help' section

### ISSUE THREAD

**Issue by davetapley** [pyinstaller/pyinstaller-hooks-contrib#700]
Following [I want to help!](https://github.com/pyinstaller/pyinstaller-hooks-contrib?tab=readme-ov-file#i-want-to-help) and mostly great but something caught me out:

If you're using a virtual environment then you need to actually install `PyInstaller` else all tests fail with e.g.:

```
src/_pyinstaller_hooks_contrib/tests/conftest.py:13: in <module>
    from PyInstaller.utils.conftest import *  # noqa: F401,F403
E   ModuleNotFoundError: No module named 'PyInstaller'
=========================================================== short test summary info ============================================================
ERROR src/_pyinstaller_hooks_contrib/tests - ModuleNotFoundError: No module named 'PyInstaller'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================== 1 error in 0.17s ===============================================================
```

Could either put it in `requirements-test.txt` or change `pip install flake8` to `pip install flake8 PyInstaller`.

Any preference?

**Comment by bwoodsend** [comment]
Hmm, good point. I think I'd prefer the latter just so that CI doesn't install PyInstaller twice – a released version from PyPI in `requirements-test.txt` and then directly from Git later on – although there's not much in that decision.

**Comment by rokm** [comment]
I also think this belongs to the documentation itself, because for any real use, you would be installing `PyInstaller` and that would pull in `pyinstaller-hooks-contrib`, not vice versa.
