### ISSUE TITLE
pyarrow

### ISSUE THREAD

**Issue by davetapley** [pyinstaller/pyinstaller-hooks-contrib#739]
**Which library is the hook for?**

`pyarrow`

**Have you gotten the library to work with pyinstaller?**

Yes, but it needs several hidden imports.

**Additional context**

I see it's supposed to be support per ⬇️ so I'm not sure if this is a regression and should be fixed there, or all hooks go here now?
- https://github.com/pyinstaller/pyinstaller/pull/4517

I need to `--hidden-import pyarrow` and `pyarrow.vendored.version` to get it working.

See also ⬇️  which mentions `pyarrow.vendored.version`.
- https://github.com/pyinstaller/pyinstaller/issues/7539

**Comment by rokm** [comment]
If you need `--hidden-import pyarrow`, you likely have another package that uses `pyarrow` and needs to be hooked. What package is that?

**Comment by davetapley** [comment]
@rokm off the top of my head, maybe `duckdb`, but it is [optional](https://github.com/duckdb/duckdb/blob/3474ee92ac3a3ee9eae68485de32b3b71f40387a/tools/pythonpkg/scripts/optional_requirements.py#L23) 🤔 

Is there a better way to check? 🙏🏻

**Comment by rokm** [comment]
What does the error traceback look like if you don't add those hidden imports?

**Comment by davetapley** [comment]
```
  File "ng\core\cache\writer.py", line 16, in write_asset
    asset.to_parquet(path, index=False)
  File "pandas\core\frame.py", line 2973, in to_parquet
  File "pandas\io\parquet.py", line 483, in to_parquet
  File "pandas\io\parquet.py", line 189, in write
  File "pyarrow\\table.pxi", line 3869, in pyarrow.lib.Table.from_pandas
  File "pyarrow\pandas_compat.py", line 572, in dataframe_to_arrays
  File "pyarrow\pandas_compat.py", line 375, in _get_columns_to_convert
  File "pyarrow\\pandas-shim.pxi", line 199, in pyarrow.lib._PandasAPIShim.is_sparse
  File "pyarrow\\pandas-shim.pxi", line 200, in pyarrow.lib._PandasAPIShim.is_sparse
  File "pyarrow\\pandas-shim.pxi", line 116, in pyarrow.lib._PandasAPIShim._have_pandas_internal
  File "pyarrow\\pandas-shim.pxi", line 104, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow\\pandas-shim.pxi", line 57, in pyarrow.lib._PandasAPIShim._import_pandas
ModuleNotFoundError: No module named 'pyarrow.vendored.version'
[19020] Failed to execute script 'cli_main' due to unhandled exception!
```

That `to_parquet` is [from pandas](https://github.com/pandas-dev/pandas/blob/008afb567b32203edaf4073f57b29b52737a2267/pandas/io/parquet.py#L394), with logic to use `pyarrow` AFAICT [here](https://github.com/pandas-dev/pandas/blob/008afb567b32203edaf4073f57b29b52737a2267/pandas/compat/pyarrow.py#L8).

Which I guess is why [this](https://github.com/pyinstaller/pyinstaller/blob/a35118319fc6048b0b4c969d91381bc244e96ee3/PyInstaller/hooks/hook-pandas.py#L15-L20) doesn't find it?

FYI it will become required in pandas upcoming 3.0, if that makes a difference:
- https://github.com/pandas-dev/pandas/issues/54466

Since `pandas` hook is in `pyinstaller` repo, should I open there instead? 🤔

**Comment by rokm** [comment]
Hmm, based on the traceback, the following example should reproduce the problem when frozen:

```python
import pandas as pd

df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df.to_parquet('test.par')
```

But it seems to work for me - can you test with your environment?

What version of python, `PyInstaller`, and `pyinstaller-hooks-contrib` are you using?

And also, what version of `pyarrow`?

**Comment by davetapley** [comment]
I could repro with that with:
```
pyinstaller==5.13.1
pyinstaller-hooks-contrib==2023.4

pandas==2.1.0
pyarrow==14.0.1
```

On Windows 11, if that matters.

**Comment by rokm** [comment]
Maybe it's time to update at least `pyinstaller-hook-contrib`? Your version does not have #662, so it's not surprising that `pyarrow.vendored.version` is not collected...
