### ISSUE TITLE
Trame suite hooks

### ISSUE THREAD

**Issue by MattTheCuber** [pyinstaller/pyinstaller-hooks-contrib#773]
**Which library is the hook for?**

[All Trame libraries](https://github.com/Kitware?q=trame-). Examples:

- `trame`
- `trame-client`
- `trame-components`
- `trame-datagrid`
- `trame-server`
- `trame-tauri`
- `trame-vtk`
- `trame-vuetify`
- `trame-xterm`

**Have you gotten the library to work with pyinstaller?**

Yes, by creating a hook for each library with the line `datas = collect_data_files("LIBRARY_NAME", subdir="module")`.

**Additional context**

Most (maybe all) Trame libraries have a data folder called `module` that needs to be collected. I was planning to create a bunch of PRs for each repo, but I thought maybe there would be a good way to get all the libraries in one-shot to future proof against new Trame libraries as they frequently come out.

**Comment by MattTheCuber** [comment]
I am happy to implement these hooks, please advise on how I should proceed.

**Comment by MattTheCuber** [comment]
Oh, I just found `trame-vtk` uses the folder name `modules`, not `module` :/

**Comment by MattTheCuber** [comment]
They are separate importable packages

**Comment by rokm** [comment]
They will need separate hooks then, one per importable package. But you can put them all in one PR (separate or one commit, up to you).

**Comment by MattTheCuber** [comment]
Can you assign this issue to me?

**Comment by rokm** [comment]
> Can you assign this issue to me?

Sure, if it makes any difference.
