### ISSUE TITLE
MONAI package

### ISSUE THREAD

**Issue by MattTheCuber** [pyinstaller/pyinstaller-hooks-contrib#777]
**Which library is the hook for?**

[MONAI](https://github.com/Project-MONAI/MONAI)

**Have you gotten the library to work with pyinstaller?**

I have gotten it to install, but there are several warnings and I did not check if the functionality works.

**Additional context**

Based on [this issue](https://github.com/Project-MONAI/MONAI/discussions/4197#discussioncomment-6632871) in the MONAI repo, I created the following hook:

```python
from pathlib import Path

import monai
from PyInstaller.utils.hooks import collect_data_files

datas = [(str(Path(monai.__file__).parent), "monai"), *collect_data_files("monai")]
```

This allows my program to build, but when I run it there are several warnings:

```
WARNING: Internal configuration path is invalid: /home/mvine/project/dist/test_library/_internal/itk
WARNING: Invalid: swig_lib: location of the swig-generated shared libraries
WARNING: Internal configuration path is invalid: /home/mvine/project/dist/test_library/_internal/itk
WARNING: Invalid: swig_py: location of the xxxPython.py swig-generated python interfaces
WARNING: Internal configuration path is invalid: /home/mvine/project/dist/test_library/_internal/itk/Configuration
WARNING: Invalid: config_py: location of xxxConfig.py CMake-generated library descriptions
```

I also don't think the datas list is optimal as it is collecting many many files and the root directory?

**Comment by rokm** [comment]
> ```
> datas = [(str(Path(monai.__file__).parent), "monai"), *collect_data_files("monai")]
> ```

Why bother calling `collect_data_files` on the package if you already brute-force collect complete package directory?

**Comment by rokm** [comment]
Hmm, looks like all this needs is source .py files collected, and this can be achieved simply by setting module collection mode.

**Comment by MattTheCuber** [comment]
How is that done?

**Comment by bwoodsend** [comment]
With [module_collection_mode](https://pyinstaller.org/en/stable/hooks.html?highlight=module_collection_mode#hook-global-variables)

**Comment by rokm** [comment]
You can take `fairscale` as an example:
https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/_pyinstaller_hooks_contrib/stdhooks/hook-fairscale.py

https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/28151eae3bc6f026c26469e0960e4aad5d689b17/tests/test_deep_learning.py#L355-L361

Note that while you can add a basic import test like I did for `fairscale`, we generally do not add torch-based packages to requirements file.

**Comment by rokm** [comment]
But do also check with your application, in case we need any hidden imports added via `collect_submodules` that are not caught by the basic import test.

**Comment by MattTheCuber** [comment]
Sure thing, I will open a pull request in a while

**Comment by MattTheCuber** [comment]
That throws the same warning about the config path and swig library...

**Comment by rokm** [comment]
Those look like they are about `itk`, not `monai`.

**Comment by rokm** [comment]
> Those look like they are about `itk`, not `monai`.

A basic `import itk` test shows that `itk/Configuration` directory is expected to exist. In the case of the test, this requires both `hiddenimports = collect_submodules('itk.Configuration')` and module collected mode for `itk.Configuration` being set to `pyz+py` (so that .py source files result in creation of the directory).

**Comment by MattTheCuber** [comment]
> module collected mode for `itk.Configuration`

By this do you mean another hook (`hook-itk.Configuration.py`) with the module collection mode specified? (Sorry for so many inquires, I'm learning)
