### ISSUE TITLE
yapf FileNotFoundError

### ISSUE THREAD

**Issue by swap-10** [pyinstaller/pyinstaller-hooks-contrib#783]
## Description of the issue
yapf is used in the groundingDINO project.
Using pyinstaller to build a onedir executable.
yapf is not included in the onedir/_internal packages, and so module not found error is encountered on running the frozen application.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.10```
* Version of Python:  3.9.13
* Platform:  Windows 11
* How you installed Python:  python.org/downloads
* Did you also try this on another platform? Does it work there? Have not tried on another platform

I have already tried adding yapf to hiddenimports.

  * [x] start with clean installation: TRIED
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it: TRIED
  * [x] Package your program in **--onedir mode**: TRIED
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.: TRIED (that's how discovered the error msg)

On manually copy-pasting the yapf module from my python installation into the onedir/_internal directory, the application works as expected.
So this seems a problem of yapf not being recognised and exported properly.

I'm using a .spec file to construct the executable.
Exe runs fine until the feature/piece of code that uses the yapf module is encountered.
### A minimal example program which shows the error

```
main.py:
import yapf

pyinstaller main.py --onedir
```
FileNotFoundError: No such file or directory: `path/to/dist/main/_internal/yapf_third_party/_ylib2to3/Grammar.txt`
### Reported earlier in pyinstaller/pyinstaller#4939 in 2020 but closed as stale

**Comment by swap-10** [comment]
Oh the base-library.zip?

And all the module-named directories like onnxruntime, torch that appear in the _internal directory are only there to keep the data files associated with those modules?

**Comment by rokm** [comment]
> Oh the base-library.zip file? Or inside the exe in the onedir mode too?

No, `base-library.zip` contains the stdlib modules that we need to initialize python interpreter and for bootstrap. The rest of pure-python modules are collected into PYZ archive, which is embedded in the executable (both in onefile and onedir modules). You can use `pyi-archive_viewer <path-to-executable>` to inspect the embedded PKG archive, and the PYZ archive that is embedded within it.

> And all the module-named directories like onnxruntime, torch that appear in the _internal directory are only there to keep the data files associated with those modules?

Yes. Data files and binaries - bundled shared libraries and binary extension modules.

**Comment by swap-10** [comment]
Sorry for returning late to this.

Very helpful details, thanks a lot! I'll check out the archive viewer as well, sounds quite useful.

> Although for some packages, like torch, we also need to collect source .py files, so you will see those in the torch directory as well...

Is this because of aten and how the python API wraps over it, or because some configs are stored in .py files?
If my package is having an issue being bundled by pyinstaller, what could be a signal that I need to do something like this (like you do for torch)?

**Comment by bwoodsend** [comment]
Torch takes plain source code and feeds it to its special JIT compiler. Occasionally, other libraries try to use source code for things they shouldn't. They will almost always be using `inspect.getsource()` which raises a fairly self explanatory `OSError: could not get source code` error.
