### ISSUE TITLE
hooks: add hook for googleapiclient.model

### ISSUE THREAD

**Issue by jrm5100** [pyinstaller/pyinstaller-hooks-contrib#99]
**Which library is the hook for?**

`statsmodels`

**Have you gotten the library to work with pyinstaller?**

Yes, but it needs several hidden imports.

**Additional context**

Based on [this comment](https://github.com/pyinstaller/pyinstaller/issues/3921#issuecomment-516895178)

**Comment by colin-fsa** [comment]
This was fixed in #100 and should be closed.

**Comment by rokm** [comment]
Indeed.
